foodadviserApi:
  image:
    repository: "foodadvisor-api"
    tag: "1.0.0"
  resplicaCount: 1
  pullPolicy: IfNotPresent
  resources: {}


foodadvisorClient:
  image:
    repository: "foodadvisor-client"
    tag: "1.0.0"
  resplicaCount: 1
  pullPolicy: IfNotPresent
  resources: {}

serviceBackend:
  type: ClusterIP
  port: 1337
  targetPort: 1337

serviceFrontend:
  type: ClusterIP
  port: 3000
  targetPort: 3000

IngressFrontend:
  annotations:
  # nginx.ingress.kubernetes.io/rewrite-target: /
  host: foodadvisor.client.com

IngressBackend:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: foodadvisor.api.com
