apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend

  {{- with .Values.IngressBackend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nignx
  rules:
    - host: {{ .Values.IngressBackend.host }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name}}-backend
                port:
                  number: {{ .Values.serviceBackend.port }}