apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.serviceBackend.name }}
spec:
    type: {{ .Values.serviceBackend.type }}
    ports:
        - port: {{ .Values.serviceBackend.port }}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app: {{ .Values.serviceBackend.selector.app }}
