apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.foodadvisorApi.service.name }}
  labels:
    {{ .Values.foodadvisorApi.labels | toYaml | nindent 4 }}
spec:
  type: {{ .Values.foodadvisorApi.service.type }}
  ports:
    - port: {{ .Values.foodadvisorApi.service.ports.port }}
      targetPort: {{ .Values.foodadvisorApi.service.ports.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{ .Values.foodadvisorApi.labels | toYaml | nindent 4 }}